export const SET_CURRENCY = 'SET_CURRENCY';
export const SET_ITEM_IN_CART = 'SET_ITEM_IN_CART';
export const UPDATE_ITEM_AMOUNT_IN_CART = 'UPDATE_ITEM_AMOUNT_IN_CART';
export const DELETE_ITEM_IN_CART = 'DELETE_ITEM_IN_CART';
